name = "AlternatingDirectionImplicit"
uuid = "15a50297-6c96-42f2-b429-f639dcf4c52e"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.1"

[deps]
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
ClassicalOrthogonalPolynomials = "b30e2e7b-c4ee-47da-9d5f-2c5c27239acd"
MatrixFactorizations = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ClassicalOrthogonalPolynomials", "MatrixFactorizations", "Test"]

